name: Deploy to Preview Channel

on:
  pull_request:

jobs:
  preview:
#    if: github.repository_owner == 'aagarwal1012'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example

    steps:
      - name: output
        run: echo ${{ github.head_ref }}
#      - uses: actions/checkout@v2
#      - uses: subosito/flutter-action@v1
#      - run: flutter build web
#      - uses: FirebaseExtended/action-hosting-deploy@v0
#        with:
#          repoToken: "${{ secrets.GITHUB_TOKEN }}"
#          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
#          expires: 30d
#          entryPoint: "./example"
#          projectId: introviews-flutter
